"""Text cleaning package: methods, density filters, and dataset cleaners."""

from .cleaning_methods import (
    COMMON_LOANWORDS,
    FOREIGN_DIACRITICS,
    FRENCH_SPANISH_STOPWORDS,
    GREEK_CHARS,
    TRIG_PATTERN,
    clean_bare_expressions,
    clean_citations,
    clean_code_assignments,
    clean_code_texts,
    clean_complexity_notation,
    clean_list_numbering,
    clean_markdown_formatting,
    clean_math_texts,
    clean_music_notation,
    clean_pipeline,
    clean_pseudocode_and_diagrams,
    clean_residual_math_noise,
    clean_url,
    contains_foreign_language,
    foreign_skip_counter,
    is_academic_content,
    is_non_prose,
    merge_continuous_equations,
    mop_up_leftover_math_and_code,
    strip_reference_list,
    strip_surrogate_characters,
)
from .placeholder_density import placeholder_density, placeholder_density_windowed
from .dataset_cleaning import (
    clean_bawe_dataset,
    clean_claude_dataset,
    clean_gemini_dataset,
    clean_mgtbench_ai_dataset,
    extract_claude_prompt_and_response,
    ingest_bawe_dataset,
    parse_bawe_xml,
)

__all__ = [
    "COMMON_LOANWORDS",
    "FOREIGN_DIACRITICS",
    "FRENCH_SPANISH_STOPWORDS",
    "GREEK_CHARS",
    "TRIG_PATTERN",
    "foreign_skip_counter",
    "placeholder_density",
    "placeholder_density_windowed",
    "clean_math_texts",
    "clean_bare_expressions",
    "clean_residual_math_noise",
    "clean_pseudocode_and_diagrams",
    "clean_code_texts",
    "clean_complexity_notation",
    "clean_list_numbering",
    "clean_markdown_formatting",
    "clean_citations",
    "clean_url",
    "strip_reference_list",
    "strip_surrogate_characters",
    "clean_music_notation",
    "merge_continuous_equations",
    "mop_up_leftover_math_and_code",
    "clean_code_assignments",
    "is_academic_content",
    "contains_foreign_language",
    "is_non_prose",
    "clean_pipeline",
    "extract_claude_prompt_and_response",
    "parse_bawe_xml",
    "ingest_bawe_dataset",
    "clean_claude_dataset",
    "clean_mgtbench_ai_dataset",
    "clean_gemini_dataset",
    "clean_bawe_dataset",
]
